// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

public class BannerExperience: MTExperience {

    public var data: BannerExperienceData {
        return broker.getData(id: id)
    }

    public var defaultData: BannerExperienceData {
        return broker.getDefaultData(id: id)
    }

    required init(id: String, parentId: String, broker: MTBroker) {
        super.init(id: id, parentId: parentId, broker: broker)

        let template = MTTemplate(
            id: "NW0bo31",
            v: "16543",
            enabled: false
        )
        register(template: template)
    }
}

public struct BannerExperienceData: MTExperienceData {
    public let label: String?

    enum CodingKeys: String, CodingKey {
        case label = "1"
    }

    public init() {
        label = nil
    }
}
