// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

public class HeaderExperience: MTExperience {

    public var data: HeaderExperienceData {
        return broker.getData(id: id)
    }

    public var defaultData: HeaderExperienceData {
        return broker.getDefaultData(id: id)
    }

    required init(id: String, parentId: String, broker: MTBroker) {
        super.init(id: id, parentId: parentId, broker: broker)

        let template = MTTemplate(
            id: "O59eW5k",
            v: "329",
            enabled: false
        )
        register(template: template)
    }
}

public struct HeaderExperienceData: MTExperienceData {
    public let bgColor: MTColor?

    enum CodingKeys: String, CodingKey {
        case bgColor = "1"
    }

    public init() {
        bgColor = nil
    }
}
