// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

public class HeaderExperience: MTExperience {

    public var data: HeaderExperienceData {
        return broker.getData(id: id)
    }

    public var defaultData: HeaderExperienceData {
        return broker.getDefaultData(id: id)
    }

    required init(id: String, parentId: String, broker: MTBroker) {
        super.init(id: id, parentId: parentId, broker: broker)

        let template = MTTemplate(
            id: "yDBpL8a",
            v: "16551",
            enabled: false
        )
        register(template: template)
    }
}

public struct HeaderExperienceData: MTExperienceData {
    public let backgroundColor: MTColor?
    public let gradientColor: MTColor?

    enum CodingKeys: String, CodingKey {
        case backgroundColor = "1"
        case gradientColor = "2"
    }

    public init() {
        backgroundColor = nil
        gradientColor = nil
    }
}
