name: samples-swiftui
options:
  bundleIdPrefix: com.deltatre
targets:
  samples-swiftui:
    sources: 
      - ./Sources
      - ./src
    type: application
    platform: iOS
    deploymentTarget: "13.0"