// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

let fallbacks = MTFallbacks(
     v: 39820,
     json: """
     {"6E4l57r":{"on":true,"sid":"0vKvPXE","v":36108,"data":"{\\"1\\":\\"Banner\\"}","pid":"O84BJ45"},"O84BJ45":{"on":true,"sid":"0pjEpkY","v":34361,"se":[{"id":"o9ykq4x","et":"ygmrAEV"},{"id":"6E4l57r","et":"Eb04Abp"}]},"o9ykq4x":{"on":true,"sid":"pjRE7z2","v":85800,"data":"{\\"1\\":\\"https://pkw.us.astcdn.com/img/sample/1=x700.jpg\\"}","pid":"O84BJ45"},"xm48x4j":{"on":true,"sid":"Jz0a90g","v":26040,"data":"{\\"1\\":{\\"opacity\\":1,\\"value\\":\\"#a56\\"}}"}}
     """
)