# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'git@github.com:CocoaPods/Specs.git'
source 'https://github.com/mtribes/client-ios.git'

target 'samples-storyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for samples-storyboard
  pod 'Mtribes'
  pod 'Kingfisher'

end
