// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

public class HomepageCollection: MTCollection {
    public let header: HeaderExperience
    public let body: HomepageBodySection

    private let childIds: [String]
    private weak var broker: MTBroker!

    init(id: String, childIds: [String], broker: MTBroker) {
        self.childIds = childIds
        self.broker = broker
        header = HeaderExperience(id: childIds[0], parentId: id, broker: broker)
        body = HomepageBodySection(id: childIds[1], parentId: id, broker: broker)

        let template = MTTemplate(
            id: "dV8NLMD",
            v: "15311",
            enabled: false
        )
        broker.register(MTNode(
            id: id,
            template: template,
            parentId: nil,
            childTypes: nil
        ))
        super.init(id: id, broker: broker, template: template)
    }
}