// Code generated by mtribes. DO NOT EDIT.

import Foundation
import Mtribes

public class HomepageBodySection: MTSection {

    enum Supported {
        typealias Hero = HeroExperience
        typealias Banner = BannerExperience
    }

    init(id: String, parentId: String, broker: MTBroker) {
        let template = MTTemplate(
            id: "5ozXdgW",
            v: "16539",
            enabled: false
        )
        super.init(id: id, parentId: parentId, broker: broker, template: template)
    }

    public override var childTypes: [String: MTExperience.Type] {
        return [
            "VGd1POB": HeroExperience.self,
            "NW0bo31": BannerExperience.self
        ]
    }
}
